version: '3.7'

services:
  backend:
    image: ejemplo-php:test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - type: bind
        source: ./reports/
        target: /app/reports/