version: '3.4'

services:
  backend:
    image: equipo01-backend-php:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mariadb:10.4.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=backend_laravel
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
